import type { INodeProperties } from "n8n-workflow";

export const properties: INodeProperties[] = [
  {
    displayName: "Resource",
    name: "resource",
    type: "options",
    noDataExpression: true,
    default: "email",
    options: [
      { name: "Account", value: "account" },
      { name: "Mailbox", value: "mailbox" },
      { name: "Email", value: "email" },
      { name: "File", value: "file" },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "get",
    displayOptions: { show: { resource: ["account"] } },
    options: [
      { name: "Get Connection", value: "get", action: "Get connection status" },
      { name: "Get Limits", value: "limits", action: "Get account limits" },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "getMany",
    displayOptions: { show: { resource: ["mailbox"] } },
    options: [
      { name: "Create", value: "create", action: "Create a mailbox" },
      { name: "Get", value: "get", action: "Get a mailbox" },
      { name: "Get Many", value: "getMany", action: "Get many mailboxes" },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "getMany",
    displayOptions: { show: { resource: ["email"] } },
    options: [
      { name: "Delete", value: "delete", action: "Delete an email" },
      {
        name: "Download Attachment",
        value: "downloadAttachment",
        action: "Download an email attachment",
      },
      {
        name: "Download Original",
        value: "downloadOriginal",
        action: "Download an original email",
      },
      { name: "Get", value: "get", action: "Get an email" },
      { name: "Get Many", value: "getMany", action: "Get many emails" },
      {
        name: "Set Read Status",
        value: "update",
        action: "Set email read status",
      },
    ],
  },
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    default: "getMany",
    displayOptions: { show: { resource: ["file"] } },
    options: [
      { name: "Delete", value: "delete", action: "Delete a file" },
      { name: "Download", value: "download", action: "Download a file" },
      { name: "Get", value: "get", action: "Get a file" },
      { name: "Get Many", value: "getMany", action: "Get many files" },
      { name: "Upload", value: "upload", action: "Upload a file" },
    ],
  },
  {
    displayName: "Mailbox ID",
    name: "mailboxId",
    type: "string",
    default: "",
    required: true,
    displayOptions: { show: { resource: ["email", "file"] } },
  },
  {
    displayName: "Mailbox ID",
    name: "mailboxId",
    type: "string",
    default: "",
    required: true,
    displayOptions: { show: { resource: ["mailbox"], operation: ["get"] } },
  },
  {
    displayName: "Email ID",
    name: "emailId",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: {
        resource: ["email"],
        operation: [
          "get",
          "update",
          "delete",
          "downloadOriginal",
          "downloadAttachment",
        ],
      },
    },
  },
  {
    displayName: "Attachment ID",
    name: "attachmentId",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: { resource: ["email"], operation: ["downloadAttachment"] },
    },
  },
  {
    displayName: "File ID",
    name: "fileId",
    type: "string",
    default: "",
    required: true,
    displayOptions: {
      show: { resource: ["file"], operation: ["get", "delete", "download"] },
    },
  },
  {
    displayName: "Email Username",
    name: "emailUsername",
    type: "string",
    default: "",
    displayOptions: { show: { resource: ["mailbox"], operation: ["create"] } },
  },
  {
    displayName: "Include Email Address",
    name: "includeEmail",
    type: "boolean",
    default: false,
    description:
      "Whether to include the receiving address (requires write permission)",
    displayOptions: { show: { resource: ["mailbox"], operation: ["get"] } },
  },
  {
    displayName: "Return All",
    name: "returnAll",
    type: "boolean",
    default: false,
    description: "Whether to return all results or only up to a given limit",
    displayOptions: {
      show: { resource: ["email", "file"], operation: ["getMany"] },
    },
  },
  {
    displayName: "Limit",
    name: "limit",
    type: "number",
    default: 50,
    typeOptions: { minValue: 1, maxValue: 10000 },
    description: "Max number of results to return",
    displayOptions: {
      show: {
        resource: ["email", "file"],
        operation: ["getMany"],
        returnAll: [false],
      },
    },
  },
  {
    displayName: "Filters",
    name: "filters",
    type: "collection",
    default: {},
    placeholder: "Add Filter",
    displayOptions: { show: { resource: ["email"], operation: ["getMany"] } },
    options: [
      {
        displayName: "Has Attachments",
        name: "has_attachments",
        type: "boolean",
        default: false,
        description: "Whether to return only emails with attachments",
      },
      {
        displayName: "Read",
        name: "read",
        type: "boolean",
        default: false,
        description: "Whether to return read emails",
      },
      { displayName: "Sender", name: "sender", type: "string", default: "" },
      {
        displayName: "Subject Contains",
        name: "subject",
        type: "string",
        default: "",
      },
    ],
  },
  {
    displayName: "Read",
    name: "read",
    type: "boolean",
    default: true,
    description: "Whether the email should be marked read",
    displayOptions: { show: { resource: ["email"], operation: ["update"] } },
  },
  {
    displayName: "Confirm Deletion",
    name: "confirm",
    type: "boolean",
    default: false,
    description: "Whether to delete this item and its stored data",
    displayOptions: {
      show: { resource: ["email", "file"], operation: ["delete"] },
    },
  },
  {
    displayName: "Input",
    name: "uploadInput",
    type: "options",
    default: "binary",
    options: [
      { name: "Binary File", value: "binary" },
      { name: "Text", value: "text" },
    ],
    displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
  },
  {
    displayName: "Input Binary Field",
    name: "inputBinaryField",
    type: "string",
    default: "data",
    required: true,
    displayOptions: {
      show: {
        resource: ["file"],
        operation: ["upload"],
        uploadInput: ["binary"],
      },
    },
  },
  {
    displayName: "Text",
    name: "text",
    type: "string",
    typeOptions: { rows: 5 },
    default: "",
    displayOptions: {
      show: {
        resource: ["file"],
        operation: ["upload"],
        uploadInput: ["text"],
      },
    },
  },
  {
    displayName: "Path",
    name: "path",
    type: "string",
    default: "",
    required: true,
    displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
  },
  {
    displayName: "Content Type",
    name: "contentType",
    type: "string",
    default: "",
    displayOptions: { show: { resource: ["file"], operation: ["upload"] } },
  },
  {
    displayName: "Output Binary Field",
    name: "outputBinaryField",
    type: "string",
    default: "data",
    required: true,
    displayOptions: {
      show: {
        operation: ["download", "downloadOriginal", "downloadAttachment"],
      },
    },
  },
  {
    displayName: "Reason",
    name: "reason",
    type: "string",
    default: "",
    displayOptions: {
      show: { operation: ["create", "upload", "update", "delete"] },
    },
  },
];
